### ISSUE TITLE
Allow/ add "TYPO3_SITE_URL" to the condition provider

### ISSUE THREAD

**Issue by EvilBMP** [b13/host_variants#8]
Currently, only "host" (`HTTP_HOST`) is available in the `SiteConditionProvider->expressionLanguageVariables`. I'd like to have the `TYPO3_SITE_URL` as well, so that a baseVariants configuration would allow to override the base by an ENV var.

For example:

```yaml
base: /
baseVariants:
  -
    base: '%env(TYPO3_BASE_URL_DOMAIN_TLD)%'
    condition: '%env(TYPO3_BASE_URL_DOMAIN_TLD)% != "" && site == "%env(TYPO3_BASE_URL_DOMAIN_TLD)%"'
  -
    base: 'https://www.domain.tld/'
    condition: 'applicationContext == "Production" && host == "www.domain.tld"'
  -
    base: 'https://live1.domain.tld/'
    condition: 'applicationContext == "Production" && host == "live1.domain.tld"'
  -
    base: 'https://dev1.domain.tld/'
    condition: 'applicationContext == "Development/Staging" && host == "dev1.domain.tld"'
  -
    base: 'https://domain.tld.ddev.site/'
    condition: 'applicationContext matches "#^Development/Local#"'
```

**Comment by EvilBMP** [comment]
Ok, this is actually not needed. We implemented it this way:

```yaml
base: https://www.domain.tld/
baseVariants:
  -
    base: '%env(TYPO3_BASE_URL_DOMAIN_TLD)%'
    condition: '"%env(TYPO3_BASE_URL_DOMAIN_TLD)%" != ""'
  -
    base: 'https://live1.domain.tld/'
    condition: 'applicationContext == "Production" && host == "live1.domain.tld"'
  -
    base: 'https://dev1.domain.tld/'
    condition: 'applicationContext == "Development/Staging" && host == "dev1.domain.tld"'
  -
    base: 'https://domain.tld.ddev.site/'
    condition: 'applicationContext matches "#^Development/Local#"'
```
